services:
  ansible:
    build: .
    container_name: ansible
    hostname: ansible
    networks:
      ansible-net:
        ipv4_address: 192.168.11.10
    volumes:
      - ./ssh:/home/vagrant/.ssh/host_keys
      - .:/home/vagrant/workspace
      - /home/vagrant/sync:/home/vagrant/sync
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    stdin_open: true
    tty: true
    privileged: true
    cgroup: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - NET_ADMIN

  database:
    build: .
    container_name: database
    hostname: database
    networks:
      ansible-net:
        ipv4_address: 192.168.11.20
    ports:
      - "8081:80"
      - "3306:3306"
      - "2220:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    privileged: true
    cgroup: host
    cap_add:
      - NET_ADMIN

  loadbalancer:
    build: .
    container_name: loadbalancer
    hostname: loadbalancer
    networks:
      ansible-net:
        ipv4_address: 192.168.11.30
    ports:
      - "8080:80"
      - "33061:3306"
      - "2221:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    privileged: true
    cgroup: host
    cap_add:
      - NET_ADMIN

  webserver:
    build: .
    container_name: webserver
    hostname: webserver
    networks:
      ansible-net:
        ipv4_address: 192.168.11.40
    ports:
      - "80:80"
      - "33062:3306"
      - "2222:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    privileged: true
    cgroup: host
    cap_add:
      - NET_ADMIN

networks:
  ansible-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1