services:
  ansible:
    build: .
    container_name: ansible
    hostname: ansible
    networks:
      ansible-net:
        ipv4_address: 192.168.11.10
    volumes:
      - ./ssh:/home/vagrant/.ssh/host_keys
      - .:/home/vagrant/workspace
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.4.4

  database:
    build: .
    container_name: database
    hostname: database
    networks:
      ansible-net:
        ipv4_address: 192.168.11.20
    ports:
      - "8081:80"
      - "3306:3306"

  loadbalancer:
    build: .
    container_name: loadbalancer
    hostname: loadbalancer
    networks:
      ansible-net:
        ipv4_address: 192.168.11.30
    ports:
      - "8080:80"
      - "33061:3306"

  webserver:
    build: .
    container_name: webserver
    hostname: webserver
    networks:
      ansible-net:
        ipv4_address: 192.168.11.40
    ports:
      - "80:80"
      - "33062:3306"

networks:
  ansible-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1