---
# This is the main playbook that will be executed when running ansible-playbook site.yml
# It includes all the roles that will be applied to the different hosts in the inventory.
# Each role is responsible for a specific part of the configuration, and they are applied to the appropriate hosts based on their group membership in the inventory file.
- hosts: control
  become: true
  roles:
    - control

- hosts: database
  become: true
  roles:
    - mysql

- hosts: loadbalancer
  become: true
  roles:
    - nginx

- hosts: webserver
  become: true
  roles:
    - apache2
    - demo_app

# After the configuration is done, we can run some checks to verify that everything is working as expected.
- hosts: database
  become: true
  roles:
    - status-database

- hosts: webserver
  become: true
  roles:
    - status-webserver

- hosts: loadbalancer
  become: true
  roles:
    - status-loadbalancer

- hosts: control
  become: true  
  roles:
    - status-control







