- name: Prueba de multiples usuarios
  hosts: all
  become: yes
  tasks:
    - name: Instalar el paquete 'python3-passlib'
      apt:
        name: python3-passlib
        state: present
    
    - name: lista multiples usuarios
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      with_items:
        - { name: usuario1, password: "contrasena1" }
        - { name: usuario2, password: "contrasena2" }
        - { name: usuario3, password: "contrasena3" }