---
- include: control.yml
- include: database.yml
- include: webserver.yml
- include: loadbalancer.yml
- include: playbook/stack_status.yml
- include: playbook/stack_restart.yml
- include: playbook/stack_status.yml