---
- hosts: control
  become: true
  gather_facts: false
  tasks:
    - name: get facts
      debug:
        var: ansible_facts

    - name: print ansible_ssh_host_key_rsa_public
      debug:
        var: ansible_facts['ssh_host_key_rsa_public']
    
    - name: print OS family
      debug:
        var: ansible_facts['os_family']
    
    - name: print distribution      
      debug:
        var: ansible_facts['distribution']
