- name: Instala Nginx cuando la maquina tenga la ip 192.168.11.30
  hosts: all
  become: true
  tasks:
    - name: Obtener la dirección IP de la interfaz eth0
      command: ip addr show eth0
      register: ip_output

    - name: Extraer la dirección IP de la salida del comando
      set_fact:
        ip_address: "{{ ip_output.stdout | regex_search('inet (\\d+\\.\\d+\\.\\d+\\.\\d+)', '\\1') }}"

    - name: Imprimir la dirección IP obtenida
      debug:
        msg: "La dirección IP de eth0 es {{ ip_address }}"

    - name: Instalar Nginx si la IP es 192.168.11.30
      apt: name=nginx state=present update_cache=yes
      when: ip_address == ['192.168.11.30']

    - name: Verificar la instalación de Nginx
      command: nginx -v
      register: nginx_version
      when: ip_address == ['192.168.11.30']
    
    - name: Imprimir la versión de Nginx instalada
      debug:
        msg: "Nginx versión: {{ nginx_version.stdout }}"
      when: ip_address == ['192.168.11.30']
    
    - name: Desinstala nginx
      apt:
        name: nginx
        state: absent
      when: ip_address == ['192.168.11.30']